### ISSUE TITLE
Not able to read the updated Master when connected Master/Slave through sentinel

### ISSUE THREAD

**Issue by UdCa-Codes** [redis/lettuce#1293]
## Bug Report
Im using Master/Slave connection through sentinel and using the below configuration to connect to redis sentinel.

#### Current Behavior

we hosted our app in kubernetes and when the master node fails for the first few times, Lettuce is responding by updating the sentinel configuration, after that its returning as error saying the "Cannot find the master node"

```java
public RedisConnectionFactory redisConnectionFactory() {
LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
                    .readFrom(MASTER)
                    .build();
            RedisSentinelConfiguration sentinelConfig = new RedisSentinelConfiguration()
                    .master("mysentinelmaster")
		    .build();    
                sentinelConfig.sentinel(xxx,6783);
            return new LettuceConnectionFactory(sentinelConfig,clientConfig);
}
@Bean
    public RedisTemplate<?, ?> redisTemplate() {
        RedisTemplate<?, ?> template = new RedisTemplate<>();
        template.setConnectionFactory(redisConnectionFactory());
        return template;
    }
```
here are the logs
```
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: Master is currently unknown: [RedisMasterSlaveNode [redisURI=RedisURI [host='xxx', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='xxx', port=6379], role=SLAVE]]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.convertLettuceAccessException(LettuceSetCommands.java:520)
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sRem(LettuceSetCommands.java:394)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.sRem(DefaultedRedisConnection.java:649)
	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy135.sRem(Unknown Source)
	at org.springframework.data.redis.core.RedisKeyValueAdapter$MappingExpirationListener.lambda$onMessage$1(RedisKeyValueAdapter.java:787)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at org.springframework.data.redis.core.RedisKeyValueAdapter$MappingExpirationListener.onMessage(RedisKeyValueAdapter.java:785)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.executeListener(RedisMessageListenerContainer.java:250)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.processMessage(RedisMessageListenerContainer.java:240)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lambda$dispatchMessage$0(RedisMessageListenerContainer.java:986)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisException: Master is currently unknown: [RedisMasterSlaveNode [redisURI=RedisURI [host='xxx', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='xxx', port=6379], role=SLAVE]]
	at io.lettuce.core.masterslave.MasterSlaveConnectionProvider.getMaster(MasterSlaveConnectionProvider.java:304)
	at io.lettuce.core.masterslave.MasterSlaveConnectionProvider.getConnectionAsync(MasterSlaveConnectionProvider.java:153)
	at io.lettuce.core.masterslave.MasterSlaveChannelWriter.write(MasterSlaveChannelWriter.java:66)
	at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:187)
	at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:152)
	at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:467)
	at io.lettuce.core.AbstractRedisAsyncCommands.srem(AbstractRedisAsyncCommands.java:1367)
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:57)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy131.srem(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sRem(LettuceSetCommands.java:392)
	... 15 common frames omitted
```
</details>

#### Expected behavior/code

Sentinel should refresh the topology continuously even after receiving updated master details from sentinel if there is some issue with the current details

#### Environment

- Lettuce version(s): [5.1.0.RELEASE]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment]
Lettuce listens continously to Sentinel Pub/Sub channels for topology updates. This approach is the most elaborate one as Sentinels actively publish changes in master and replica configuration. Can you provide a simple, reproducible test case or the logs from the time of the failover until the command failure?

**Comment by UdCa-Codes** [comment]
@mp911de  I face that issue intermittently , I tried it few times and here are the logs that i see.
Steps:
1. I failed the redis Master and it recovered fine.
2. Brought the master up and brought down master again.
3. Intermittently i face the below errors.:
Im actually unsure if there is something im missing in the configuration or it is a bug.

`
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 10 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.convertLettuceAccessException(LettuceKeyCommands.java:817)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.del(LettuceKeyCommands.java:131)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.del(DefaultedRedisConnection.java:69)
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy197.del(Unknown Source)
	at org.springframework.data.redis.core.RedisKeyValueAdapter.lambda$put$0(RedisKeyValueAdapter.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at org.springframework.data.redis.core.RedisKeyValueAdapter.put(RedisKeyValueAdapter.java:223)
	at org.springframework.data.keyvalue.core.KeyValueTemplate.lambda$insert$0(KeyValueTemplate.java:164)
	at org.springframework.data.keyvalue.core.KeyValueTemplate.execute(KeyValueTemplate.java:346)
	at org.springframework.data.keyvalue.core.KeyValueTemplate.insert(KeyValueTemplate.java:157)
	at org.springframework.data.redis.core.RedisKeyValueTemplate.insert(RedisKeyValueTemplate.java:158)
	at org.springframework.data.keyvalue.core.KeyValueTemplate.insert(KeyValueTemplate.java:140)
	at org.springframework.data.keyvalue.repository.support.SimpleKeyValueRepository.save(SimpleKeyValueRepository.java:101)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy135.save(Unknown Source)
	at xxxxxxx
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 10 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy131.del(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceKeyCommands.del(LettuceKeyCommands.java:129)
	... 48 common frames omitted

`

**Comment by UdCa-Codes** [comment]
@mp911de I face that issue intermittently , I tried it few times and here are the logs that i see.
Steps:

1.I failed the Redis Master and it recovered fine.
2.Brought the master up and brought down master again.

 i face the below errors after repeating the above steps few times(attached the logs
[Redis Issue.pdf](https://github.com/lettuce-io/lettuce-core/files/4712127/Redis.Issue.pdf)
)

Im actually unsure if there is something im missing in the configuration or it is a bug.
Or should i manually trigger the Topology Refresh or Pub/Sub channels from my configuration?

**Comment by maiconbaumx** [comment]
Hello guys!
We're facing the same issue described by @UdCa-Codes in our setup, which actually consists in a master-slave setup with Sentinel. 

This is the driver configuration we're using:

```
application.store.master-name=<master-name>
application.store.hosts=<sentinel-address>
application.store.port=<sentine-port>
application.store.username=<username>
application.store.password=<password>
application.store.commandTimeout=15s
```
We're using the version 6.0.1, but we're facing this issue for a long time in other versions. 
Seems to happens quite randomly. From the Redis perspective, the Master election occurs with no erros and we're able to login in the Sentinel and discover the master normally through redis-cli for example. From the application perspective, sometimes we need to reboot it to effectively discover the Master through Sentinel.

In the application's log we see this kind of message:

```
Master is currently unknown: [RedisUpstreamReplicaNode [redisURI=redis://****@<previous-master-IP> role=REPLICA], RedisUpstreamReplicaNode [redisURI=redis://****@<previous-replica-IP>, role=REPLICA]]
```

Is there some kind of debugging we can do to get more information from the driver itself?

**Comment by siwyd** [comment]
I don't know if it's completely related, but we faced a bit of a similar issue some time ago where newly started applications would sometimes complain about not finding a master and staying in a broken state. The only way to 'fix' them was by sending a SENTINEL RESET to one of the Sentinel servers, so all clients would get info sent by the Sentinels. We couldn't quite figure out what was going wrong through the debug logging. After more digging, we did stumble upon a change some time ago where we reduced the Redis timeout from 10s to 1s. After reverting this change, the problem stopped occurring.

**Comment by perlun** [comment]
I am seeing the same (or a similiar) issue as this. I think my scenario was roughly the following (this was on my local dev setup, luckily):

1. Redis Sentinel processes were killed (by me manually)
2. One of the Redis nodes was firewalled (`sudo iptables -A INPUT -p tcp --dport 6379 -j DROP`)
3. Our application was then connecting to the Redis Sentinel cluster, using Lettuce 5.3.0 and some connect code that looks similar to this (manually recreated, the actual code is spread out over multiple places in our case and conditionalized to support both single-node and Sentinel setups):

   ```java
           Builder redisUriBuilder = RedisURI.builder()
                .withSentinelMasterId( sentinelMasterId) )
                .withPassword( password );

           redisUriBuilder.withSentinel( host1, port, password) );
           redisUriBuilder.withSentinel( host2, port, password) );
           redisUriBuilder.withSentinel( host3, port, password) );

           RedisURI redisUri = redisUriBuilder.build();

           Builder clientResourcesBuilder = DefaultClientResources.builder();

           if ( computationThreadPoolSize > 0 ) {
               clientResourcesBuilder.computationThreadPoolSize( computationThreadPoolSize );
           }

           if ( ioThreadPoolSize > 0 ) {
               clientResourcesBuilder.ioThreadPoolSize( ioThreadPoolSize );
           }

           RedisClient redisClient = RedisClient.create( clientResourcesBuilder.build() );
           redisClient.setDefaultTimeout( Duration.ofMillis( connectionTimeout ) );

            StatefulRedisMasterReplicaConnection<String, byte[]> redisConnection = MasterReplica.connect(
                    redisClient,
                    StringByteArrayCodec.INSTANCE,
                    redisUri
            );

            redisConnection.setTimeout( Duration.ofMillis( redisServer.getCommandTimeout() ) );
            redisConnection.setReadFrom( redisSentinelServer.readFrom() );
   ```

With this in place, Lettuce continuously fails to reconnect to the master node _if_ it was down on the initial connection. Here is the stack trace (up until the first application-level line):

```
io.lettuce.core.RedisException: Master is currently unknown: [RedisMasterSlaveNode [redisURI=RedisURI [host='192.168.97.13', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='192.168.97.11', port=6379], role=SLAVE]]
	at io.lettuce.core.masterslave.MasterSlaveConnectionProvider.getMaster(MasterSlaveConnectionProvider.java:309)
	at io.lettuce.core.masterslave.MasterSlaveConnectionProvider.getConnectionAsync(MasterSlaveConnectionProvider.java:158)
	at io.lettuce.core.masterslave.MasterSlaveChannelWriter.write(MasterSlaveChannelWriter.java:66)
	at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:187)
	at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:169)
	at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:472)
	at io.lettuce.core.AbstractRedisAsyncCommands.set(AbstractRedisAsyncCommands.java:1223)
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:57)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy47.set(Unknown Source)
	at fi.hibox.centre.module.job.rediscachepopulator.managers.RedisCrudManager.lambda$upsertEntity$0(RedisCrudManager.java:55)
```

The proper Redis master node is on 192.168.97.12 in this case, but Lettuce fails to ever realize it. Issuing a `SENTINEL RESET *` command manually seemed to help it, but... I'd much rather see it self-heal of course.

---

@mp911de Is my assumption that the fact that the 192.168.97.12 node was unavailable on startup, and Lettuce hence removed it from its list of "potential master nodes" anyway near correct, or is this a false assumption on my behalf? The Sentinel nodes was also down when the connection was made, so... could it be that it never connected to the Sentinel nodes in this case? (only to the Redis nodes). This would be one plausible theory about why it never would receive the pub/sub toplogy update in this case. Note, only guessing, I haven't looked at the Lettuce internals in this case. OTOH, issuing the Sentinel reset manually did indeed make it work, so I guess it must have been connected to Sentinel at that point at least...

Could it be like this: Sentinel was down when it first tried to connect => Lettuce never got the initial pub/sub topology update/updates. Once Lettuce had managed to connect it, all was fine in terms of _subsequent_ topology updates, but the actual update/updates when the 192.168.97.12 was made the master was gone => it never managed to recover.

Distributed systems are indeed hard... :smile:

**Comment by perlun** [comment]
> Could it be like this: Sentinel was down when it first tried to connect => Lettuce never got the initial pub/sub topology update/updates. Once Lettuce had managed to connect it, all was fine in terms of subsequent topology updates, but the actual update/updates when the 192.168.97.12 was made the master was gone => it never managed to recover.

Another theory: it could actually have been that 192.168.97.12 was actually already the master. When it was firewalled => no other master could be elected. Once it came back again, the Redis slaves would reconnect to it nicely. _But_ no topology update was posted, since the topology didn't actually change. (it was more a matter of "master came back", it was just the fact that Lettuce had never managed to connect to this node.)

**Comment by tushartvg** [comment]
We are also facing the same issue with the master-slave sentinel setup. Using lettuce 5.2.2.RELEASE.
Is there any update on this?

**Comment by Steven520xiaowei** [comment]
We are also facing the same issue using lettuce 5.1.8.RELEASE.

**Comment by parmar049** [comment]
I am also facing same issue. Currently using 6.1.9 version. We recently introduced Master Slave concept, before we were just connecting to master node.
We are using Spring class `org.springframework.data.redis.connection.RedisStaticMasterReplicaConfiguration` for configuration. 
Everything seems to be fine , but we noticed that in AWS ECS 2 out of 16 instances started throwing error 

exception is `io.lettuce.core.RedisException: Master is currently unknown: [RedisMasterReplicaNode [redisURI=rediss://replica.prod-redis-cluster.XXXXXX.euw1.cache.amazonaws.com:6379?timeout=200000000ns, role=REPLICA]]`

Also some logs here:
`Caused by: io.lettuce.core.RedisException: Cannot determine topology from [rediss://master.prod-redis-cluster.XXXXXX.euw1.cache.amazonaws.com:6379?timeout=200000000ns, rediss://replica.prod-redis-cluster.XXXXXX.euw1.cache.amazonaws.com:6379?timeout=200000000ns]
	at io.lettuce.core.masterreplica.StaticMasterReplicaConnector.lambda$connectAsync$0(StaticMasterReplicaConnector.java:72)`

Not able to identify the cause , but for temporary fix have to restart the service and then it went well after that.
But after few days again same issue arrive. I can't restart every time for this issue.

**Comment by tishun** [comment]
Folks, to do any progress on this issue we would need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that could help pinpoint the problem.
Until then we can only speculate what the issue is.

**Comment by amish-meesho** [comment]
Faced same issue and I believe updating to lettuce version 6.3.0.RELEASE or later will fix this issue.
Attaching bug info: https://github.com/redis/lettuce/issues/2082
Bug fix code: https://github.com/redis/lettuce/pull/2499

**Comment by panas-sydor-ei** [comment]
I've faced a similar issue with a master-slave setup with a shared connection. I'm using Lettuce version `6.3.2.RELEASE` (but I've tested and it reproduces with `6.8.2.RELEASE` and `7.2.1.RELEASE` as well).

It happens when there are connection issues to the master during the connection initialization (i.e., first write operation). In this case, we get `io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1/<unresolved>:6379`. And during all subsequent write operations, we are getting a master unknown exception: `io.lettuce.core.RedisException: Master is currently unknown: [RedisMasterReplicaNode [redisURI=rediss://127.0.0.1:6380?verifyPeer=NONE&timeout=500000000ns, role=REPLICA]]`.

For me, this behaviour is somewhat undesirable, as if there are any connection issues during service startup, the master will not be resolved, and the only solution is to restart the service (which can be a bit of a pain when you have a lot of instances rolling frequently).

I would prefer it to be handled the same as when an already initialized connection is dropped. Then the retry mechanism is initialized, and when the node is back connection is successfully recovered.

Is this a bug or by design?

By the way, there is a similar issue with the Replica connection. In case it's down during the connection innitialization then all further read operations will be done from the master node, even if the replica node is recovered.

**Comment by amish-meesho** [comment]
@panas-sydor-ei I have faced this similar issue and it got resolved in my case after increasing the command-timeout to 100ms as previously I was using 25ms and also used keep-alive flag as true.

Reason behind increasing command-timeout : I have seen that sentinel/redis was not able to perform complete set of operations (like passing master info to the lettuce) within 25ms so increased it.

But in your case, it;s already high for the local address so I would suggest you to check from the DB side and till then can you add keep-alive config flag..

**Comment by panas-sydor-ei** [comment]
@amish-meesho The localhost is only used as an example to reproduce the issue. We have this issue in our environments. The issue is not around the connection or command timeout. This may happen even with a high enough connection timeout due to network lag (especially on non-prod environments). In my case, with the localhost, I intentionally keep the master down during the first write operation to reproduce the issue, and then bring it back in, but further write operations keep failing with `Master is currently unknown`. So the question here is more about how the initial connection failure is handled, and whether there is a way to configure a retry for this case, the same as when an already initialized connection drops.
