### ISSUE TITLE
Lettuce unable to connect to Replica endpoint

### ISSUE THREAD

**Issue by kalyanghosh** [redis/lettuce#2312]
## Bug Report
Hi,

We have a redis setup with 1 Primary and 2 Replicas in cluster disabled mode. The issue is as follows:
1. When we connect to the primary endpoint and set `ReadFrom.MASTER`, we are able to connect and do `get/put`
2. But when we set `ReadFrom.REPLICA` with endpoint still as primary (as redis docs mention that, we can use any node endpoint), the connection to the redis endpoint fails with the below stack trace.

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
// io.lettuce.core.RedisConnectionException: Unable to connect to redis://primary-endpoint
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.masterreplica.MasterReplica.getConnection(MasterReplica.java:261)
	at io.lettuce.core.masterreplica.MasterReplica.connect(MasterReplica.java:113)
	at com.twilio.voiceconoptionsstatusservice.server.redis.RedisClusterClient.getStatefulRedisPrimaryReplicaConnection(RedisClusterClient.java:67)
	at com.twilio.voiceconoptionsstatusservice.server.redis.RedisClusterClient.<init>(RedisClusterClient.java:31)
	at com.twilio.voiceconoptionsstatusservice.server.application.VoiceconOptionsStatusServiceApplication.run(VoiceconOptionsStatusServiceApplication.java:151)
	at com.twilio.voiceconoptionsstatusservice.server.application.VoiceconOptionsStatusServiceApplication.run(VoiceconOptionsStatusServiceApplication.java:42)
	at com.twilio.coreutil.service.dw20.application.DW20ApplicationAdapter.run(DW20ApplicationAdapter.java:44)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at com.twilio.voiceconoptionsstatusservice.server.application.VoiceconOptionsStatusServiceApplication.main(VoiceconOptionsStatusServiceApplication.java:172)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to primary_endpoint.voicecon-redis.w28m8h.use1.cache.amazonaws.com:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.RedisClient.lambda$transformAsyncConnectionException$22(RedisClient.java:781)
	at io.lettuce.core.DefaultConnectionFuture.lambda$thenCompose$1(DefaultConnectionFuture.java:253)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.lettuce.core.AbstractRedisClient.lambda$null$5(AbstractRedisClient.java:458)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.lettuce.core.protocol.RedisHandshakeHandler.lambda$fail$4(RedisHandshakeHandler.java:131)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:756)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:611)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.CompletionException: io.lettuce.core.RedisCommandTimeoutException: Connection initialization timed out. Command timed out after 1 minute(s)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	... 31 more
Caused by: io.lettuce.core.RedisCommandTimeoutException: Connection initialization timed out. Command timed out after 1 minute(s)
	at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:71)
	at io.lettuce.core.protocol.RedisHandshakeHandler.lambda$channelRegistered$0(RedisHandshakeHandler.java:62)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	... 4 more

```

</details>

#### Input Code
The java client used is as follows:

<details>
<summary>Input Code</summary>

```java
// final String primaryRedisEndpoint = redisConfiguration.getPrimaryEndpoint();

        final RedisURI redisURI =
                RedisURI.Builder.redis(primaryRedisEndpoint)
                        .withPort(6379)
                        .withSsl(true)
                        .withVerifyPeer(false)
                        .build();

        final RedisClient redisClient = RedisClient.create(redisURI);
        final StatefulRedisMasterReplicaConnection<String, String>
                statefulRedisPrimaryReplicaConnection =
                MasterReplica.connect(redisClient, StringCodec.UTF8, redisURI);

        // set read from primary
        statefulRedisPrimaryReplicaConnection.setReadFrom(ReadFrom.REPLICA);
        logger.info("Connection to redis successful during application startup.");

        return statefulRedisPrimaryReplicaConnection;
```

</details>

#### Expected behavior/code

1. Ideally we should be able to connect to replica endpoint normally and perform read from replicas.
2. We can connect to the replica endpoint fine from the service host using `aws-cli` and perform `get/put`

#### Environment

- `Redis 6.1.10`

**Comment by tishun** [comment]
@kalyanghosh is this issue still relevant?

Have you been able to connect to `primary_endpoint.voicecon-redis.w28m8h.use1.cache.amazonaws.com:6379` from the same container/machine that is running the client using the redis-cli (to verify there are no network connectivity issues)?

**Comment by kalyanghosh** [comment]
Hi,
You can close the issue.

Thanks,
Kalyan
