### ISSUE TITLE
No enum constant io.lettuce.core.pubsub.PubSubOutput.Type.PONG

### ISSUE THREAD

**Issue by hongshulin1990** [redis/lettuce#2400]
#### Current Behavior
when my application restart will trigger listenerTopics rebanlance which must invoke RedisMessageListenerContainer.setMessageListeners(Collections.unmodifiableMap(listenerTopics) method,but redis server response a PONG type message and dispatch to PubSubCommandHandler, and PubSubCommandHandler does not recongnize the "PONG" message

<details>
<summary>

```java
Caused by: java.lang.IllegalArgumentException: No enum constant io.lettuce.core.pubsub.PubSubOutput.Type.PONG
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at io.lettuce.core.pubsub.PubSubOutput$Type.valueOf(PubSubOutput.java:35) ~[lettuce-core-6.2.4.RELEASE.jar!/:6.2.4.RELEASE]
	at io.lettuce.core.pubsub.PubSubOutput.set(PubSubOutput.java:92) ~[lettuce-core-6.2.4.RELEASE.jar!/:6.2.4.RELEASE]
	at io.lettuce.core.output.ReplayOutput$BulkString.replay(ReplayOutput.java:128) ~[lettuce-core-6.2.4.RELEASE.jar!/:6.2.4.RELEASE]
	at io.lettuce.core.output.ReplayOutput.replay(ReplayOutput.java:83) ~[lettuce-core-6.2.4.RELEASE.jar!/:6.2.4.RELEASE]
	at io.lettuce.core.pubsub.PubSubCommandHandler.complete(PubSubCommandHandler.java:160) ~[lettuce-core-6.2.4.RELEASE.jar!/:6.2.4.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:682) ~[lettuce-core-6.2.4.RELEASE.jar!/:6.2.4.RELEASE]
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:112) ~[lettuce-core-6.2.4.RELEASE.jar!/:6.2.4.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:599) ~[lettuce-core-6.2.4.RELEASE.jar!/:6.2.4.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	... 1 more</summary>
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java

    @Resource(name = "clusterRedisMessageListenerContainer")
    private RedisMessageListenerContainer clusterMessageListenerContainer;

    messageListenerContainer.setMessageListeners(Collections.unmodifiableMap(listenerTopics));
```

</details>

#### Expected behavior/code

subscribe successfully and receive pubsub messge

#### Environment

- Lettuce version(s): 6.2.2.RELEASE
- Redis version: Redis 5.0

**Comment by mp911de** [comment]
Do you have a reliable way to reproduce the problem? I'm not able to reproduce the issue.

**Comment by hongshulin1990** [comment]
its not easy to reproduce, the main code snippet is as follows:

```java
{

	@Resource
	private RedisMessageListenerContainer messageListenerContainer;

	@Autowired
	private List<MessageListenerAdapter> messageListenerAdapters;

	@Test
	public void PubSubTest() {
		List<String> ownerships = new ArrayList<>() {{add("1");add("2");add("5");}};
		if (messageListenerAdapters != null) {
			Map<MessageListenerAdapter, Set<Topic>> listenerTopics = messageListenerAdapters.stream()
					.filter(messageListenerAdapter -> !(messageListenerAdapter instanceof KlineListener))
					.collect(Collectors.toMap(messageListenerAdapter -> messageListenerAdapter,
							messageListenerAdapter -> messageListenerAdapter.shardingTopic(ownerships)));

			log.info("registerMessageListener {}", listenerTopics);
			messageListenerContainer.setMessageListeners(Collections.unmodifiableMap(listenerTopics));
			log.info("standalone redis resubscribes success");
		}
	}

}
```

there are two random situations:
* 1. when the messageListenerContainer.setMessageListeners(Collections.unmodifiableMap(listenerTopics)) was invoked, the exception java.lang.IllegalArgumentException: No enum constant io.lettuce.core.pubsub.PubSubOutput.Type.PONG occurs randomly 
 * 2. when the exception previously mentioned appears, most of the time, the redis server data can be subscribed normally,and in a few cases, these topics set  cannot be subscribed successfully; but debug log always shows suscribe is sucess.
 ```java
class: 
org.springframework.data.redis.listener.RedisMessageListenerContainer
level: 
DEBUG
line: 
324
msg: 
RedisMessageListenerContainer listeners registered successfully
```
