### ISSUE TITLE
Intermittent error reporting RedisCommandTimeoutException and We found some problems by catching the bag

### ISSUE THREAD

**Issue by woxiangjingjing1314** [redis/lettuce#2437]
#### Current Behavior
When using lettuce, our service periodically reports a RedisCommandTimeoutException when redis commands are executed. We caught found that after establish a TCP connection, the client 5 seconds after sent redis server authentication instructions, redis server can normal response, but at this time because we set the timeout time is 5 seconds, will quote RedisCommandTimeoutException. My question is why after establishing the connection, it took 5 seconds to send the authentication instruction?

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```
2023-07-04 17:10:14.105|ERROR|1055|taskExecutor-42|svp-hlsparser||||com.timi.clipcloud.svphlspaser.service.impl.ParserHlsServiceImplV2.syncM3u8-156|Redis command timed out; nested exception is io.lettuce.core.**RedisCommandTimeoutException: Command timed out**
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:257)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:718)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:63)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:210)
	at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:52)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:59)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:48)
	at com.timi.clipcloud.core.cache.redis.RedisHelper.get(RedisHelper.java:164)
	at com.timi.clipcloud.svphlspaser.service.impl.ParserHlsServiceImplV2.getMaxGmtRedis(ParserHlsServiceImplV2.java:185)
	at com.timi.clipcloud.svphlspaser.service.impl.ParserHlsServiceImplV2.syncM3u8(ParserHlsServiceImplV2.java:95)
	at com.timi.clipcloud.svphlspaser.service.impl.ParserHlsServiceImplV2$$FastClassBySpringCGLIB$$a379c2bc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.timi.clipcloud.svphlspaser.service.impl.ParserHlsServiceImplV2$$EnhancerBySpringCGLIB$$982636ac.syncM3u8(<generated>)
	at com.timi.clipcloud.svphlspaser.job.StartHlsPaserJob$StartHlsPaserThread.run(StartHlsPaserJob.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:118)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy228.get(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:61)
	... 22 common frames omitted

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): 5.0.5.RELEASE
- Redis version: [e.g. 4.0.9]

#### Additional context
**These are the results of our bag grab！**
<img width="947" alt="63b02bc29dfdf34bd27cf72c12b807e" src="https://github.com/lettuce-io/lettuce-core/assets/46334239/c2403fa5-a156-4986-822f-4b8eafc0a673">

**Comment by qlma3** [comment]
**This is our configuration**

spring:
    lettuce:
      pool:
        max-active: 300  
        max-wait: 60000ms
        max-idle: 10
        min-idle: 1
    timeout: 5000ms

**Comment by mp911de** [comment]
If you encounter this kind of issues, please collect a profiling including a thread dump to record the state. Without details, I'm not able to diagnose where the problem comes from.

**Comment by qlma3** [comment]
> 

Do you need jvm stack logs for java? After we restarted the java service, we are not reporting this problem at present, and it has been running normally for 6 hours.

**Comment by qlma3** [comment]
> If you encounter this kind of issues, please collect a profiling including a thread dump to record the state. Without details, I'm not able to diagnose where the problem comes from.

![error](https://github.com/lettuce-io/lettuce-core/assets/46334239/b99c8094-12d0-4f60-9348-78ee22a58695)

Can this log help you find the problem

**Comment by tishun** [comment]
> 
> Can this log help you find the problem

Not really. There is no way to ascertain what caused the timeout. Profiling the code during one of these issues could help, but without more data it would be hard to pinpoint the issue.
