### ISSUE TITLE
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

### ISSUE THREAD

**Issue by adar-v** [redis/lettuce#2910]
#### Current Behavior

The concurrent request volume of one of my online services is very high, and this netty problem occasionally occurs. Each time it occurs only on one of the pods, it will recover after restarting. I can confirm that this is related to the operation of redis. But I have no idea how to solve it. When this error occurs, all subsequent operations will fail. At this time, the second error will be reported.
I can't reproduce this problem.

<details>
<summary>Stack trace</summary>

```java
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:600)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
reactiveRedisTemplate.opsForValue()
                .multiGet(keyList)
                .flatMap(item -> {
                //     Service code。
                })
```

</details>

#### Environment

- Lettuce version(s): 6.1.8.RELEASE
- Redis version: 5.0.6

**Comment by tishun** [comment]
Seems very similar to https://github.com/netty/netty/issues/12777

Not sure if we can do anything until it is resolved.

**Comment by tishun** [comment]
Will monitor for changes in the netty thread

**Comment by tishun** [comment]
Seems we already have a similar report in #2542

**Comment by tishun** [comment]
Let's keep the conversation in #2542 
If you believe this is a different issue please reopen.
