### ISSUE TITLE
Occasionally seeing NoSuchElementException

### ISSUE THREAD

**Issue by himanshu0791** [redis/lettuce#2934]
## Bug Report

java.util.NoSuchElementException: null at java.util.Arrays$ArrayItr.next(Arrays.java:4245) at io.lettuce.core.output.KeyValueListOutput.set(KeyValueListOutput.java:80) at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:810) at io.lettuce.core.protocol.RedisStateMachine.handleBytes(RedisStateMachine.java:572) at i.l.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:206) at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:334) at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:295) at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:842) at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:793) at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:767) at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:659) at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:599) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) at i.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at i.n.c.e.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) at i.n.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ... 1 common frames omitted Wrapped by: java.util.concurrent.CompletionException: java.util.NoSuchElementException at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.lang.Thread.run(Thread.java:840)

This shows time to time on our logs on v6.2.2

**Comment by tishun** [comment]
Hey @himanshu0791 ,
to help you we will need more information on how / when this happens.
Are you able to reproduce it somehow? What is the code that causes it?

Simply by looking in to the stack trace it would be hard to know what the issue is.

**Comment by tishun** [comment]
Similar stack trace as the one in #2121
Will need to investigate further

**Comment by moishy90** [comment]
I was running into the same issue in version 6.2.4. Upgrading to 6.4.0 resolved the issue.

**Comment by tishun** [comment]
Since 6.2.x is very old I think we should not keep this open.

Please reopen if you reproduce with a more recent version and please provide as much details as possible so we can work on it.
