### ISSUE TITLE
Lettuce 6.5.0.RELEASE does not provide the StatefulRedisConnectionImpl constructor that used to be provided in 6.4.0

### ISSUE THREAD

**Issue by tishun** [redis/lettuce#3054]
## Bug Report

See https://github.com/redis/lettucemod/issues/62

#### Current Behavior

The implementation of the RedisJSON commands introduced a new parser abstraction.
It is required to build the StatefulRedisConnectionImpl, but it used to not be part of the contract.

#### Expected behavior/code

We should avoid deprecating public API, especially without prior notice

**Comment by mmoayyed** [comment]
@tishun Thank you for working on this. I think there are still compatibility issues.

Trying 6.5.1, I see the following:

```
java.lang.NoSuchMethodError: 'void io.lettuce.core.RedisAsyncCommandsImpl.<init>(io.lettuce.core.api.StatefulRedisConnection, io.lettuce.core.codec.RedisCodec)'
	at com.redis.lettucemod.RedisModulesAsyncCommandsImpl.<init>(RedisModulesAsyncCommandsImpl.java:75)
	at com.redis.lettucemod.StatefulRedisModulesConnectionImpl.newRedisAsyncCommandsImpl(StatefulRedisModulesConnectionImpl.java:50)
	at com.redis.lettucemod.StatefulRedisModulesConnectionImpl.newRedisAsyncCommandsImpl(StatefulRedisModulesConnectionImpl.java:30)
	at io.lettuce.core.StatefulRedisConnectionImpl.<init>(StatefulRedisConnectionImpl.java:104)
	at io.lettuce.core.StatefulRedisConnectionImpl.<init>(StatefulRedisConnectionImpl.java:84)
	at com.redis.lettucemod.StatefulRedisModulesConnectionImpl.<init>(StatefulRedisModulesConnectionImpl.java:41)
	at com.redis.lettucemod.RedisModulesClient.newStatefulRedisConnection(RedisModulesClient.java:249)
	at com.redis.lettucemod.RedisModulesClient.newStatefulRedisConnection(RedisModulesClient.java:48)
	at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:290)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:220)
	at com.redis.lettucemod.RedisModulesClient.connect(RedisModulesClient.java:198)
	at com.redis.lettucemod.RedisModulesClient.connect(RedisModulesClient.java:183)
```

**Comment by tishun** [comment]
My bad. It was a huge change, should have checked all possible places.
Let me add this as another task.
